# Tubes Mata Kuliah Kecerdasan Buatan

## kelompok 2 : "Prediksi Prestasi Akademik Siswa Menggunakan Machine Learning Berdasarkan Faktor Demografis dan Kehadiran"

Link Dataset: https://www.kaggle.com/datasets/waqi786/student-performance-dataset/data

Anggota :
1. Rakasya Yoga
2. R. Rafi Yudi Pramana
3. Datu reksa Hamza Putra
4. M. Ali Abdillah Khotami
5. Aditya

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

Kode di atas digunakan untuk mengimport library-library yang dibutuhkan, seperti numpy untuk perhitungan numerik (array), pandas untuk dataframe, plt dan sns untuk visualisasi, dan sklearn untuk modelling

In [7]:
df = pd.read_csv("../dataset/student_performance_data_baru.csv")
df.head()

Gender  Age  StudyHoursPerWeek  AttendanceRate  PartTimeJob  \
0       1   24                 37           90.75            1   
1       0   22                 37           74.90            0   
2       1   22                 10           53.36            0   
3       1   24                 10           70.26            1   
4       1   18                 19           74.87            1   

   ExtraCurricularActivities  GPA  
0                          0  3.5  
1                          0  2.5  
2                          0  2.5  
3                          0  3.5  
4                          0  2.5

Kode di atas digunakan untuk membaca dataset yang akan digunakan, yaitu student_performance_data.csv. Kemudian 5 data teratas ditampilkan menggunakan head.

dalam data tersebut terdapat Kolom-kolom sebagai berikut:

1. StudentID: Nomor identitas unik setiap mahasiswa  
2. sex: Jenis kelamin mahasiswa (0 = perempuan, 1 = laki-laki)  
3. Age: Usia mahasiswa  
4. StudyHoursPerWeek: Jumlah jam belajar per minggu  
5. AttendanceRate: Persentase kehadiran mahasiswa di kelas  
6. GPA: Indeks prestasi kumulatif mahasiswa  
7. PartTimeJob: Status pekerjaan paruh waktu (0 = tidak bekerja, 1 = bekerja)  
8. ExtraCurricularActivities: Keterlibatan dalam kegiatan ekstrakurikuler (0 = tidak ikut, 1 = ikut)



## Data Exploration

In [13]:
df = pd.read_csv("../dataset/student_performance_data_baru.csv")

# FEATURE SELECTION
X = df.drop("GPA", axis=1)  # hapus features
y = df["GPA"].astype(str)  # kelas label

# DATA SPLIT
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# FEATURE SCALING
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
# MODEL TRAINING
# Naive Bayes
model_nb = GaussianNB()
model_nb.fit(X_train_scaled, y_train)
pred_nb = model_nb.predict(X_test_scaled)

# Decision Tree
model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)
pred_dt = model_dt.predict(X_test)

# SVM
model_svm = SVC(kernel='rbf', C=1, gamma='scale')
model_svm.fit(X_train_scaled, y_train)
pred_svm = model_svm.predict(X_test_scaled)

# Random Forest
model_rf = RandomForestClassifier(n_estimators=150, random_state=42)
model_rf.fit(X_train, y_train)
pred_rf = model_rf.predict(X_test)


## MODEL PERFORMANCE COMPARISON

In [21]:
print("Naive Bayes")
print("Accuracy:", round(accuracy_score(y_test, pred_nb), 4))
print(classification_report(y_test, pred_nb))
print("-" * 50)

# CONFUSION MATRIX
print("\nConfusion Matrices:")
cm = confusion_matrix(y_test, pred_nb)
print("Naive Bayes")
print(cm)

Naive Bayes
Accuracy: 0.31
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00        12
         2.5       0.31      0.64      0.41        28
         3.0       0.00      0.00      0.00        18
         3.5       0.32      0.42      0.36        31
         4.0       0.00      0.00      0.00        11

    accuracy                           0.31       100
   macro avg       0.12      0.21      0.15       100
weighted avg       0.18      0.31      0.23       100

--------------------------------------------------

Confusion Matrices:
Naive Bayes
[[ 0  8  0  4  0]
 [ 0 18  0 10  0]
 [ 0 10  0  8  0]
 [ 0 18  0 13  0]
 [ 0  5  0  6  0]]


C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics

In [20]:
print("Decision Tree")
print("Accuracy:", round(accuracy_score(y_test, pred_dt), 4))
print(classification_report(y_test, pred_dt))
print("-" * 50)

# CONFUSION MATRIX
print("\nConfusion Matrices:")
cm = confusion_matrix(y_test, pred_dt)
print("Decision Tree")
print(cm)

Decision Tree
Accuracy: 0.24
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00        12
         2.5       0.19      0.25      0.22        28
         3.0       0.24      0.33      0.28        18
         3.5       0.29      0.26      0.27        31
         4.0       0.38      0.27      0.32        11

    accuracy                           0.24       100
   macro avg       0.22      0.22      0.22       100
weighted avg       0.23      0.24      0.23       100

--------------------------------------------------

Confusion Matrices:
Decision Tree
[[ 0  8  1  3  0]
 [ 2  7  8  8  3]
 [ 1  3  6  7  1]
 [ 0 13  9  8  1]
 [ 0  5  1  2  3]]


In [24]:
print("SVM")
print("Accuracy:", round(accuracy_score(y_test, pred_svm), 4))
print(classification_report(y_test, pred_svm))
print("-" * 50)

# CONFUSION MATRIX
print("\nConfusion Matrices:")
cm = confusion_matrix(y_test, pred_svm)
print("SVM")
print(cm)

SVM
Accuracy: 0.27
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00        12
         2.5       0.27      0.54      0.36        28
         3.0       1.00      0.06      0.11        18
         3.5       0.25      0.35      0.29        31
         4.0       0.00      0.00      0.00        11

    accuracy                           0.27       100
   macro avg       0.30      0.19      0.15       100
weighted avg       0.33      0.27      0.21       100

--------------------------------------------------

Confusion Matrices:
SVM
[[ 0  7  0  5  0]
 [ 0 15  0 13  0]
 [ 0 10  1  7  0]
 [ 0 20  0 11  0]
 [ 0  3  0  8  0]]


C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics

In [23]:
print("Random Forest")
print("Accuracy:", round(accuracy_score(y_test, pred_rf), 4))
print(classification_report(y_test, pred_rf))
print("-" * 50)

# CONFUSION MATRIX
print("\nConfusion Matrices:")
cm = confusion_matrix(y_test, pred_rf)
print("Random Forest")
print(cm)

Random Forest
Accuracy: 0.33
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00        12
         2.5       0.32      0.57      0.41        28
         3.0       0.22      0.11      0.15        18
         3.5       0.40      0.45      0.42        31
         4.0       0.50      0.09      0.15        11

    accuracy                           0.33       100
   macro avg       0.29      0.25      0.23       100
weighted avg       0.31      0.33      0.29       100

--------------------------------------------------

Confusion Matrices:
Random Forest
[[ 0  7  2  3  0]
 [ 1 16  3  7  1]
 [ 1  7  2  8  0]
 [ 2 13  2 14  0]
 [ 0  7  0  3  1]]


In [18]:
# EVALUATION
models = {
    "Naive Bayes": pred_nb,
    "Decision Tree": pred_dt,
    "SVM": pred_svm,
    "Random Forest": pred_rf
}

print("\n====== MODEL PERFORMANCE COMPARISON ======\n")
for name, pred in models.items():
    print(f"📌 {name}")
    print("Accuracy:", round(accuracy_score(y_test, pred), 4))
    print(classification_report(y_test, pred))
    print("-" * 50)

# OPTIONAL: CONFUSION MATRIX
print("\nConfusion Matrices:")
for name, pred in models.items():
    cm = confusion_matrix(y_test, pred)
    print(f"\n{name}:\n{cm}")


====== MODEL PERFORMANCE COMPARISON ======

📌 Naive Bayes
Accuracy: 0.31
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00        12
         2.5       0.31      0.64      0.41        28
         3.0       0.00      0.00      0.00        18
         3.5       0.32      0.42      0.36        31
         4.0       0.00      0.00      0.00        11

    accuracy                           0.31       100
   macro avg       0.12      0.21      0.15       100
weighted avg       0.18      0.31      0.23       100

--------------------------------------------------
📌 Decision Tree
Accuracy: 0.24
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00        12
         2.5       0.19      0.25      0.22        28
         3.0       0.24      0.33      0.28        18
         3.5       0.29      0.26      0.27        31
         4.0       0.38      0.27      0.32        11

    accuracy                 

C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Rakasya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics